### ISSUE TITLE
Sorry, I can not download normals_gt.tgz！！！！！！

### ISSUE THREAD

**Issue by JuanJia** [TUI-NICR/EMSANet#2]
Access forbidden!
You don't have permission to access the requested object. It is either read-protected or not readable by the server.

If you think this is a server error, please contact the [webmaster](mailto:helpdesk@cims.nyu.edu).

Error 403
[cs.nyu.edu](https://cs.nyu.edu/)
Apache/2.4.6

**Comment by danielS91** [comment]
It looks like that the precomputed normals are no longer available. 

We are working on a fix to make the normal extraction optional.
